initdb CLI, Docker for local env, local setup steps in README
Nukesor/ultimate-poll-bot pull request #75
Opened 2020-05-29 15:45 UTC by JosXa

2020-05-29 15:57 UTC, Nukesor requested changes
Eine kleine mini Anmerkung, danach sieht das tip-top aus.

Danke schon mal für die Contribution!!!

2020-05-29 15:57 UTC, Nukesor commented on README.md
> +1. Execute `poetry install` to install all dependencies.
Wie gut. Wusste nicht dass das mit `1.` geht :D
TIL

2020-05-29 15:57 UTC, Nukesor commented on pollbot/config.py
> +        "sql_uri": "postgres://pollbot:localhost/pollbot",
Ich würd tatsächlich den `pollbot:` kram eher weg lassen.
Von den bisherigen Setups hab ich selten Docker gesehen.
Die meisten User connecten tatsächlich über ihren eigenen Username auf Postres.

2020-05-29 22:40 UTC, JosXa commented on pollbot/config.py
> +        "sql_uri": "postgres://pollbot:localhost/pollbot",
Wollte es halt direkt freundlich mit dem Docker container konfigurieren, sodass die direkt miteinander zusammenspielen können 🤔 Und da kenn ich natürlich den Benutzernamen noch nicht

2020-05-29 22:54 UTC, JosXa commented on pollbot/config.py
> +        "sql_uri": "postgres://pollbot:localhost/pollbot",
> Von den bisherigen Setups hab ich selten Docker gesehen.

Ja gut, vielleicht weil keiner ihnen direkt n docker-compose hingestellt hat das sie einfach nur ausführen müssen :D

2020-05-30 11:19 UTC, Nukesor commented on pollbot/config.py
> +        "sql_uri": "postgres://pollbot:localhost/pollbot",
Ich dachte nur es wäre nice, da das der default ist.
Nicht jeder benutzt Docker.

Aber an sich ist mir das komplett schnuppe, ich hab mein stehendes Setup. Wenn Docker noch immer das Ding ist, dann macht das halt so.

2020-05-30 11:20 UTC, merged